### ISSUE TITLE
Error should go back to happy state, after a successful API call

### ISSUE THREAD

**Issue by deadprogram** [hybridgroup/commander#68]
![erroricon](http://i.imgur.com/KfpavDf.png)

The indicator that shows errors "!" should go back to the "i" icon after a successful API call to a connected device. Right now it appears like it never clears.

**Comment by deadprogram** [comment]
Further info: this only happens when the API endpoint being called does not return `'ok'`, not sure if this is by intent, but it does not seem to be documented anywhere.

**Comment by luisgodinez** [comment]
This was cause by an issue on cylon library @deadprogram, it should be fixed now, closing the issue.
